spring.application.name=task-service
server.port=8082

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/javaLabTask
spring.r2dbc.username=postgres
spring.r2dbc.password=pgsql
spring.r2dbc.driver=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka